### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by murugan425** [next-demo/doctor-appointment-service#5]
- [x] next-demo/doctor-appointment-ui#2
- [x] next-demo/doctor-appointment-service#7
- [x] next-demo/doctor-appointment-service#8
